import Head from "next/head";
import Hero from "./components/Hero/Hero";
import TopBar from "./components/organisms/TopBar/TopBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>SuperApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />
      <Hero />
    </>
  );
}
